### ISSUE TITLE
数据库名称为大写时候，无法自识别表名及列名自动补全功能

### ISSUE THREAD

**Issue by zhituanchen** [jooksoft/jookdb#3]
您好：
   发现连接MySQL数据库库名是大写的时候，无法自识别表名及列名自动补全功能，这个请问怎么解决呢；
小写库名是可以的：
![image](https://github.com/jooksoft/jookdb/assets/71009460/21e5bcb3-6e35-4718-a9d0-104f59a9f763)
大写库名是不行的：
![image](https://github.com/jooksoft/jookdb/assets/71009460/e46461fd-513a-4d46-adb8-c652e020902e)

**Comment by jooksoft** [comment]
这个问题可以修复，会在下个版本解决
